export let cars = [
  {
    id: 'toyota-rav4',
    name: 'Toyota RAV4',
    image: '/images/Gmail/IMG_3456.jpeg',
    desc: 'Berline confortable et économique, idéale pour les trajets urbains et interurbains.',
    price_person: '10 000 FCFA',
    priceDay: '35 000 FCFA',
    priceMonth: 'Sur devis',
    seats: 5,
    transmission: 'Manuelle',
    ac: true
  },
  {
    id: 'toyota-rav4-noir',
    name: 'Toyota RAV4 Noir',
    image: '/images/Gmail/IMG_3457.webp',
    desc: 'SUV robuste et polyvalent, parfait pour affronter tous types de routes au Sénégal.',
    priceDay: '35 000 FCFA',
    priceMonth: 'Sur devis',
    seats: 5,
    transmission: 'Manuelle',
    ac: true
  },
  {
    id: 'avensis-break',
    name: 'Avensis Break',
    image: '/images/Gmail/IMG_3462.jpeg',
    desc: 'Offrant un confort exceptionnel pour vos voyages.',
    priceDay: '30 000 FCFA',
    priceMonth: 'Sur devis',
    seats: 5,
    transmission: 'Manuelle',
    ac: true
  },
  {
    id: 'avensis-break-royal',
    name: 'Avensis Break Royal',
    image: '/images/Gmail/IMG_3463.jpeg',
    desc: 'Berline de luxe pour vos déplacements professionnels ou événements spéciaux.',
    priceDay: '30 000 FCFA',
    priceMonth: 'Sur devis',
    seats: 5,
    transmission: 'Manuelle',
    ac: true
  },
  {
    id: 'toyota-rav4-blanc',
    name: 'Toyota RAV4 Blanc',
    image: '/images/Gmail/IMG_3467.jpeg',
    desc: "SUV élégant et spacieux, idéal pour les familles ou les groupes d'amis en voyage.",
    priceDay: '35 000 FCFA',
    priceMonth: 'Sur devis',
    seats: 5,
    transmission: 'Manuelle',
    ac: true
  }
];

export let trips = [
  {
    id: 'stlouis-aeroport',
    from: 'Saint-Louis',
    to: 'Aéroport',
    departure: 'Tous les jours - H24',
    perPerson: false,
    price: '50 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
  {
    id: 'aeroport-stlouis',
    from: 'Aéroport',
    to: 'Saint-Louis',
    perPerson: false,
    departure: 'Tous les jours - H24',
    price: '50 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
  {
    id: 'dakar-stlouis',
    from: 'Dakar',
    to: 'Saint-Louis',
    perPerson: true,
    departure: 'Tous les jours - H24',
    price_person: '10 000 FCFA',
    price: '55 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
  {
    id: 'stlouis-dakar',
    from: 'Saint-Louis',
    to: 'Dakar',
    perPerson: true,
    departure: 'Tous les jours - H24',
    price_person: '10 000 FCFA',
    price: '55 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
  {
    id: 'stlouis-ziguinchor',
    from: 'Saint-Louis',
    to: 'Ziguinchor',
    perPerson: false,
    departure: 'Tous les jours - H24',
    price: '225 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
  {
    id: 'stlouis-thies',
    from: 'Saint-Louis',
    to: 'Thies',
    perPerson: true,
    departure: 'Tous les jours - H24',
    price_person: '9 000 FCFA',
    price: '50 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
  {
    id: 'stlouis-saly',
    from: 'Saint-Louis',
    to: 'Saly',
    perPerson: true,
    departure: 'Tous les jours - H24',
    price_person: '12 500 FCFA',
    price: '55 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
  {
    id: 'stlouis-bandia',
    from: 'Saint-Louis',
    to: 'Bandia',
    perPerson: false,
    departure: 'Tous les jours - H24',
    price: '50 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
  {
    id: 'stlouis-palmarin',
    from: 'Saint-Louis',
    to: 'Palmarin',
    perPerson: false,
    departure: 'Tous les jours - H24',
    price: '100 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
  {
    id: 'stlouis-sine-saloum',
    from: 'Saint-Louis',
    to: 'Sine-Saloum(Keur Samba DIA Mangane)',
    perPerson: false,
    departure: 'Tous les jours - H24',
    price: '100 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
  {
    id: 'stlouis-tamba',
    from: 'Saint-Louis',
    to: 'Tambacounda',
    perPerson: false,
    departure: 'Tous les jours - H24',
    price: '125 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
  {
    id: 'stlouis-parc-djoudj',
    from: 'Saint-Louis',
    to: 'Parc Djoudj',
    perPerson: false,
    departure: 'Tous les jours - H24(Aller - retour)',
    price: '40 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
  {
    id: 'stlouis-podor',
    from: 'Saint-Louis',
    to: 'Podor',
    perPerson: false,
    departure: 'Tous les jours - H24',
    price: '60 000 FCFA',
    seats: 4,
    type: 'Véhicule climatisée',
  },
];